### ISSUE TITLE
Missing the extraction of texture dimension on storage textures

### ISSUE THREAD

**Issue by Jiawei-Shao** [google/shaderc#1007]
Current SPVC [does not extract the texture dimension on the storage textures](https://github.com/google/shaderc/blob/master/libshaderc_spvc/src/spvc.cc#L981), which is needed in the validations on the storage textures inside Dawn.

@kainino0x  @Kangz @zoddicus PTAL, thanks!

**Comment by zoddicus** [comment]
I can look at this on Monday.

Is the non spvc version of this already in Dawn?
What are the specific sourcing cross elements that you need exposed?

**Comment by Jiawei-Shao** [comment]
Hi @zoddicus, 

This is needed in https://dawn-review.googlesource.com/c/dawn/+/17167, which has been reverted after SPVC is enabled by default in Dawn.

I have verified a fix like https://github.com/google/shaderc/pull/1008 is enough for me to re-land this patch. PTAL, thanks!
