### ISSUE TITLE
CMake Warning (dev) at cmake/utils.cmake:110 (get_target_property)

### ISSUE THREAD

**Issue by dneto0** [google/shaderc#101]
When configuring on Mac with bootstrapped-from-source cmake, I get this:

-- Found Google Mock, building tests.
CMake Warning (dev) at cmake/utils.cmake:110 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "glslang".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

Call Stack (most recent call first):
  cmake/utils.cmake:105 (get_transitive_libs)
  cmake/utils.cmake:127 (get_transitive_libs)
  libshaderc/CMakeLists.txt:30 (combine_static_lib)
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by antiagainst** [comment]
Tried on macOS. Didn't see this. I think it was resolved somehow. Closing.
