### ISSUE TITLE
Add spvc API for renaming SPIR-V binding decoration.

### ISSUE THREAD

**Issue by austinEng** [google/shaderc#1015]
In Dawn, we read the SPIR-V binding decorations and convert sparse bindings to packed indices.
For Metal, this is a [packed array of shader indices](https://source.chromium.org/chromium/chromium/src/+/master:third_party/dawn/src/dawn_native/metal/ShaderModuleMTL.mm;l=144?q=ShaderModuleMTL.mm&ss=chromium&originalUrl=https:%2F%2Fcs.chromium.org%2F). For D3D12, we have a [packed array of binding offsets](https://source.chromium.org/chromium/chromium/src/+/master:third_party/dawn/src/dawn_native/d3d12/ShaderModuleD3D12.cpp;l=104?q=ShaderModuleD3D12&ss=chromium&originalUrl=https:%2F%2Fcs.chromium.org%2F)

The offset or index is set as a decoration on the binding and is output as part of the shader transpilation.

We'd like to do the same amount of packing in the Vulkan backend so that we can deduplicate the VkDescriptorSetLayouts that are the same modulo binding numbers. We'd need SPVC to have a way to output SPIR-V with modified binding numbers so we can do this type of packing.

@zoddicus

**Comment by zoddicus** [comment]
spvc has been deprecated and removed.
