### ISSUE TITLE
shaderc_compile_options_add_macro_definition doesn't copy macro name and value

### ISSUE THREAD

**Issue by dekimir** [google/shaderc#104]
The blurb for this function promises that name/value can be modified or deleted after it returns.  But that's currently not true: the underlying implementation merely keeps pointers to name/value.  The function should obey its contract.

**Comment by Qining** [comment]
I think we can solve this by either 1) changing the MacroDictionary in libshaderc_util/compiler.h from string_piece to std::string, or 2) have an having another 'dictionary' in libshaderc. I think changing the MacroDictionary is better.

**Comment by dekimir** [comment]
Agreed we should just change `MacroDictionary`.
