### ISSUE TITLE
Kokoro not running on shaderc PRs

### ISSUE THREAD

**Issue by Kangz** [google/shaderc#1092]
For example in #1091 the only check was from CLA assistant, but there was no kokoro runs. I think Kokoro CI broke with the rename of the branch to "main".

**Comment by zoddicus** [comment]
This may not be a master -> main thing. It doesn't look like the kokoro:run label was added to the PR.

This is not added by default to non-member PRs to prevent spurious invocations of the bots. It needs to be added by the reviewer for non-member PRs.

I will check that the bots are working next week when I am back.

**Comment by Kangz** [comment]
Oh sorry, that's my bad and I should have known that. This is probably not a kokoro problem then.
