### ISSUE TITLE
Is compiling GLSL containing the line `#extension GL_KHR_shader_subgroup_basic: enable` supported?

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [google/shaderc#1103]
I have encountered an issue using a library which depends on this library.

My issue: [How to include `GL_` extensions?](https://github.com/vulkano-rs/vulkano/issues/1395)

I am trying to figure out where the issue lies.

Right now I'm simply asking the question which is the title of this issue.

> Is compiling GLSL containing the line `#extension GL_KHR_shader_subgroup_basic: enable` supported?

Essentialy, does my problem reside in the code of `shaderc`?

The GLSL code which doesn't compile from my original issue:

```GLSL
#version 450

#extension GL_KHR_shader_subgroup_basic: enable

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0,binding = 0) buffer Buffer {
    uint x[];
};

void main() {
    uint indx = gl_GlobalInvocationID.x;
    uint holder = gl_SubgroupID;
}
```

Apoligies for my inexperience here, even starting out as a primarily C++ dev it is difficult for me to read and understand a lot of the shaderc code.

**Comment by zoddicus** [comment]
@dneto0 Do you know the answer to this?

**Comment by JonathanWoollett-Light** [comment]
@zoddicus @dneto0 Has there been any looking into this? I'm a little cautious to spend quite a bit of time learning and relearning a bunch of stuff to be able to dig this up myself.

**Comment by JonathanWoollett-Light** [comment]
To answer my own issue after quite a while, it certainly is possible and the failure/bug lies with the library I was using previously.
