### ISSUE TITLE
Bug: user-provided #line directives are ignored

### ISSUE THREAD

**Issue by Crisspl** [google/shaderc#1114]
Not sure if this is not an issue for glslang.
Anyway... user-provided `#line` directives seems to be ignored while generating another `#line`s during insterting contents of `#include`d sources (that's what I think is happening). Example input:
```
#version 430 core

layout (location = 0) in vec3 Pos;
layout (location = 0) out vec3 outPos;

#line 1 "test.glsl"

#include "g.glsl"

vec3 whatever()
{
	return vec4(1.0); //cannot convert return value to function return type
}

void main()
{
	gl_Position = Pos.xyzz;
}
```
I'm getting error reported in line 12, which is correct assuming there's no `#line 1` at line 6. So expected result is error reported at line 6.

**Comment by zoddicus** [comment]
@dneto0 This sounds like either a glslc or glslang issue.

**Comment by Crisspl** [comment]
False alert, the problem was on our side. Sorry.
