### ISSUE TITLE
Build fails if python venv is a project local directory

### ISSUE THREAD

**Issue by udnaan** [google/shaderc#1137]
## What
Build fails with a plethora of copyright messages such as 
`./.venv/lib/python3.8/site-packages/cmake/data/share/cmake-3.18/Modules/CMakeCompilerABI.h  has no copyright message.`

## Where
Debian Linux X86_64, Python 3.8.5, Virtual environment inside `$PROJECT_DIR/.venv`

## Why
Apparently the script add_copyright.py tries to indiscriminately check for copyright header inside all directories and files

## Potential Fix
Within the same script, the function filtered_descendants can be modified to detect virtual environment
```
def filtered_descendants(glob):
    """Returns glob-matching filenames under the current directory, but skips
    some irrelevant paths."""
    filter_list = ['third_party', 'external', 'build*', 'out*', 'CompilerIdCXX']
    venv_dir = os.environ.get('VIRTUAL_ENV', None)
    if venv_dir:
        filter_list.append(os.path.basename(venv_dir))
    return find('.', glob, filter_list)
```

**Comment by ben-clayton** [comment]
FWIW: [`license-checker`](https://github.com/google/shaderc/pull/1104/commits) was added recently, and may be able to entirely replace `add_copyright.py`

**Comment by udnaan** [comment]
Sounds good. Perhaps this can stay up until that happens in case someone else runs into this.
