### ISSUE TITLE
Inconsistent error messages depending on the type of error

### ISSUE THREAD

**Issue by expipiplus1** [google/shaderc#1154]
With files foo and bar with respective contents

```
foo
```

```
float3 main(){
  return a;
}
```

observe that the format of the error messages differs:

```
$ glslc -fshader-stage=frag -x hlsl foo -o foo.spv
foo: foo(1): error at column 3, HLSL parsing failed.

$ glslc -fshader-stage=frag -x hlsl bar -o foo.spv
bar:2: error: 'a' : unknown variable
bar:2: error: 'return' : type does not match, or is not convertible to, the function's return type
2 errors generated.
```

**Comment by dneto0** [comment]
The error on the 'foo' file is being generated with a different message format than for most other messages.
I think that's a bug in Glslang, but I'll keep this open to track.

**Comment by dneto0** [comment]
Indeed, for HLSL compilation Glslang generates a different message format for some cases.

If the source file is foo.comp.hlsl, then we get:

```
$ glslangValidator -V -D foo.comp.hlsl -o foo.spv
foo.comp.hlsl
foo.comp.hlsl(1): error at column 3, HLSL parsing failed.
ERROR: 1 compilation errors.  No code generated.


SPIR-V is not generated for failed compile or link
```
And through glslc:

```
$ glslc -fshader-stage=comp -x hlsl foo.comp.hlsl
foo.comp.hlsl: foo.comp.hlsl(1): error at column 3, HLSL parsing failed.
```

**Comment by dneto0** [comment]
Hmm.
The comment at that point in Glslang is fairly deliberate that it's better for automatic integration with a UI.
See https://github.com/KhronosGroup/glslang/blob/f7c43377f095b96cec8b374ef04120c4b86864f6/glslang/HLSL/hlslParseHelper.cpp#L135 

So I think the onus is on Shaderc to adapt to this outlier case.

**Comment by dneto0** [comment]
This gets even more curious.
It looks like the problem is that no detailed message is actually provided.
Example session:
```
$ cat foo.comp.hlsl
foo
$ glslangValidator -V -D foo.comp.hlsl
foo.comp.hlsl
foo.comp.hlsl(1): error at column 3, HLSL parsing failed.
ERROR: 1 compilation errors.  No code generated.


SPIR-V is not generated for failed compile or link
$ cat foo:bar.comp.hlsl
float3 main(){
  return a;
}
$ glslangValidator -V -D foo:bar.comp.hlsl
foo:bar.comp.hlsl
ERROR: foo:bar.comp.hlsl:2: 'a' : unknown variable 
ERROR: foo:bar.comp.hlsl:2: 'return' : type does not match, or is not convertible to, the function's return type 
foo:bar.comp.hlsl(2): error at column 11, HLSL parsing failed.
ERROR: 3 compilation errors.  No code generated.


SPIR-V is not generated for failed compile or link
```

So now I'm back to thinking that Glslang should be emitting a regular detailed error in this case. It's just that the code is so malformed that it gets confused, it seems.

**Comment by dneto0** [comment]
This is to be solved in Glslang.
