### ISSUE TITLE
Support C-Style intializers

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [google/shaderc#1164]
I have the following code

```glsl
nbl_glsl_MC_instr_stream_t nbl_glsl_MC_oriented_material_t_getEvalStream(in nbl_glsl_MC_oriented_material_t orientedMaterial)
{
	return nbl_glsl_MC_instr_stream_t{ orientedMaterial.instr_offset,orientedMaterial.rem_pdf_count };
}
```
or (which should also be supported)

```glsl
nbl_glsl_MC_instr_stream_t nbl_glsl_MC_oriented_material_t_getEvalStream(in nbl_glsl_MC_oriented_material_t orientedMaterial)
{
	return { orientedMaterial.instr_offset,orientedMaterial.rem_pdf_count };
}
```

I get the following erroe message
`nbl/builtin/glsl/material_compiler/common_invariant_declarations.glsl:101: error: '' :  syntax error, unexpected LEFT_BRACE, expecting LEFT_PAREN`

The initializers are core since GLSL version 4.30
https://stackoverflow.com/questions/52070904/does-glsl-support-c-style-initializers-or-not

P.S. Constructor "style" intialization works
```
return nbl_glsl_MC_instr_stream_t( orientedMaterial.instr_offset,orientedMaterial.rem_pdf_count );
```

**Comment by zoddicus** [comment]
This sounds like it might be a gslang issue, @dneto0 can you take a look?

**Comment by dneto0** [comment]
Hey @devshgraphicsprogramming I think you are mistaken.

Your first example uses 
syntax like   `foo{value}` which is like calling a C++11 constructor using a brace-init-list.  See [cppreference](https://en.cppreference.com/w/cpp/language/constructor).

Your second example uses syntax like `return {value};` which is like case 8 of C++11 list-initialization. See [cppreference](https://en.cppreference.com/w/cpp/language/list_initialization).

What GLSL 4.3 supports is its own syntax, which is more like C-style initialization.
Check the uses of the _initializer_ grammar term in the [GLSL 4.3 spec](https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.30.pdf).
You'll find that it's only used in one of the following cases:

- preceded by an EQUALS token
- preceded by a COMMA token in the initializer-list production
- preceded by a LEFT_BRACE token in the intializer production (transitively through initializer_list).

So the syntax you're using is not parf of GLSL.
