### ISSUE TITLE
Vulkan GLSL variants should support "h" for half constants.

### ISSUE THREAD

**Issue by alecazam** [google/shaderc#1191]
We have some pretty ugly code trying to use half support in Vulkan's GLSL variant.   Since the GLSL is a variant anyways, can the syntax support the "h" designator?  If not, then at least transpiling these casts away would make Metal/HLSL shaders a little more readable.

This is how ugly GLSL looks with all of these casts:

color.a *= mix( half(1.0), pow( abs( myvalue ), half(3.0) ), half(othervalue) );

This is how it would look in Metal/HLSL:  Although rumor has it HLSL replaces 1.0h with float, and requires ugly min16float casts.  Metal works fine with h notation.  I really want the original source to look like this, but we can strip the casts away since they're just defines to float16_t.

color.a *= mix( 1.0h, pow( abs( myvalue ), 3.0h), half(othervalue) );

**Comment by alecazam** [comment]
I find the whole highp/medium/lowp to be noise that this point.  Most of the hardware has moved onto fp32 only, or fp32+fp16.  So it's about time GLSL supported the HLSL/MSL style float2/3/4 and half/2/3/4 (and double2/3/4).  The current vec2/3/4 isn't scalable, hence GLSL's already less readable/typeable float16_t/f16vec2/3/4 and foat64_t/f64vec2/3/4.

**Comment by dneto0** [comment]
Those are requests for changes to the GLSL language.
That should be filed on https://github.com/KhronosGroup/GLSL/issues

If/when it becomes a GLSL feature or extension, then it would be implemented in Glslang github.com/KhronosGroup/glslang and then that would be automatically picked up by Shaderc builds.

**Comment by alecazam** [comment]
Seems that transpiling is the domain of glslc or at least spirv-opt.  That's why the second proposal was to have the transpiling handle this.  That requires no mods to GLSL, since that could be a lengthy process.
