### ISSUE TITLE
How to build Shaderc from source ?

### ISSUE THREAD

**Issue by jiapei100** [google/shaderc#1278]
I tried to build Shaderc from source, but obtained the following ERROR messages.

```console
[ 85%] Update build-version.inc in the Shaderc build directory (if necessary).
/usr/bin/python3 ....../shaderc/utils/update_build_version.py ....../shaderc ....../shaderc/build/build-version.inc
usage: ....../shaderc/utils/update_build_version.py <shaderc-dir> <spirv-tools-dir> <glslang-dir> <output-file>
make[2]: *** [CMakeFiles/build-version.dir/build.make:74: CMakeFiles/build-version] Error 1
make[2]: Leaving directory '....../shaderc/build'
make[1]: *** [CMakeFiles/Makefile2:257: CMakeFiles/build-version.dir/all] Error 2
make[1]: Leaving directory '....../shaderc/build'
make: *** [Makefile:149: all] Error 2
```

Did anybody meet the same issue?

**Comment by jiapei100** [comment]
Problem solved: [https://github.com/google/shaderc/pull/1279](https://github.com/google/shaderc/pull/1279)

**Comment by ben-clayton** [comment]
`usage: ....../shaderc/utils/update_build_version.py <shaderc-dir> <spirv-tools-dir> <glslang-dir> <output-file>`

Is suggesting that `update_build_version.py` is unhappy with the arguments. It looks like you've trimmed the paths with `......`, so I have to speculate here - but do you have whitespaces in your directory paths?
