### ISSUE TITLE
Upcoming branch rename in SPIRV-Cross

### ISSUE THREAD

**Issue by HansKristian-Work** [google/shaderc#1293]
IIRC, shaderc pulls in SPIRV-Cross as a module:

Just a heads up that this is happening soon in case something needs to change: https://github.com/KhronosGroup/SPIRV-Cross/issues/2081.

**Comment by dneto0** [comment]
actually Shaderc doesn't.  But Chromium's vulkan-deps does.
I already have a tracking bug for that.

Thanks for the heads-up!
