### ISSUE TITLE
dll support for windows?

### ISSUE THREAD

**Issue by pixeljetstream** [google/shaderc#130]
is there intention to create official dll support for shaderc?

the header could get a prefix similar to how GLFW for example handles dll import/export
https://github.com/glfw/glfw/blob/master/include/GLFW/glfw3.h#L182

**Comment by dekimir** [comment]
There are no current plans for it, but only because we're prioritizing other work first.  We can keep this issue open to track it.

**Comment by httpdigest** [comment]
I am also very much in favor of being able to build a shared library from libshaderc. Also the LWJGL project would like to add Java bindings to it and link to it dynamically.

**Comment by chrisvarns** [comment]
I think this issue can be closed, I am able to build, link and use `shaderc_shared.lib` and `shaderc_shared.dll` on the current known-good

**Comment by antiagainst** [comment]
Thanks, @chrisvarns!

**Comment by feliwir** [comment]
@chrisvarns how did you actually manage that? When i enable "BUILD_SHARED_LIBS" i get `CMake Error at third_party/glslang/StandAlone/CMakeLists.txt:49 (install):
  install Library TARGETS given no DESTINATION!`
