### ISSUE TITLE
Support for atomic float operations in HLSL shaders?

### ISSUE THREAD

**Issue by rcoreilly** [google/shaderc#1305]
Is there a way to use atomic float operations in HLSL input files?  I tried using the functions from the MS directx spec: https://microsoft.github.io/DirectX-Specs/d3d/HLSL_SM_6_6_Int64_and_Float_Atomics.html  but these didn't work.  I tried specifying the `--target-env=vulkan1.3`. Here's the different ops I tried, based on random googling:

```
	I[[vk::binding(5, 1)]] RWStructuredBuffer<float> GBuf; 
...
	InterlockedExchange(GBuf[10], 1);
	InterlockedCompareStoreFloatBitwise(GBuf[10], 1, 2, 2);
	OpAtomicFAddEXT(GBuf[10], 1);
	atomicAdd(GBuf[10], 1);
```

I tried adding various incantations of `#extension EXT_shader_atomic_float : enable`  with `HLSL` or `GLSL` or `GL` or nothing as a prefix, none of which were accepted: e.g., `warning: '#extension' : extension not supported: HLSL_EXT_shader_atomic_float`

**Comment by rcoreilly** [comment]
I'm not sure what exactly happened but somehow I can now get the extension to work without complaining:

```
#extension GL_EXT_shader_atomic_float : enable
```

and in grepping through the source code (the only way to really answer questions I suppose) it looks like it should be `atomicAdd`, but it still complains about that:

```
error: 'atomicAdd' : no matching overloaded function found
1 error generated.
```

**Comment by dneto0** [comment]
Shaderc wraps around Glslang.  Questions about its language support should go there.
https://github.com/KhronosGroup/glslang 

I believe the focus for HLSL compilation in Glslang has been for SM 5.1.
For SM 6.0 and above you should look to DXC and its followons.
