### ISSUE TITLE
Thank you for the DEPS file. Please keep the layout the same.

### ISSUE THREAD

**Issue by hydra3333** [google/shaderc#1307]
Thank you for the DEPS file.
https://github.com/google/shaderc/blob/main/DEPS

I process it (old fashioned text manipulation, not json parsing) to determine commit id's for the other dependencies when I need to build them first.

Would you please consider not changing the text formatting/layout of the DEPS file ?

Thank you.

**Comment by dneto0** [comment]
You're welcome!

We don't plan to change the format.

If you run into difficulty, it is valid Python.
