### ISSUE TITLE
Support for extension limits from VK_EXT_mesh_shader

### ISSUE THREAD

**Issue by rsahlin** [google/shaderc#1311]
Hi

I'm using glslc (VulkanSDK 1.3.239.0) to compile Vulkan shaders and would like to be able to include limits for VK_EXT_mesh_shader, for instance the MaxMeshWorkGroupSize and MaxTaskWorkGroupSize, as parameters to `-flimit=`

Currently I get compiler error:
glslc: error: -flimit error: invalid resource limit: MaxTaskWorkGroupSizeX_EXT

Running the command `--show-limits` and comparing the result to configuration dump from glslangValidator shows that the following limits are missing:

```
MaxMeshOutputVerticesNV 256
MaxMeshOutputPrimitivesNV 512
MaxMeshWorkGroupSizeX_NV 32
MaxMeshWorkGroupSizeY_NV 1
MaxMeshWorkGroupSizeZ_NV 1
MaxTaskWorkGroupSizeX_NV 32
MaxTaskWorkGroupSizeY_NV 1
MaxTaskWorkGroupSizeZ_NV 1
MaxMeshViewCountNV 4
MaxMeshOutputVerticesEXT 256
MaxMeshOutputPrimitivesEXT 256
MaxMeshWorkGroupSizeX_EXT 128
MaxMeshWorkGroupSizeY_EXT 128
MaxMeshWorkGroupSizeZ_EXT 128
MaxTaskWorkGroupSizeX_EXT 128
MaxTaskWorkGroupSizeY_EXT 128
MaxTaskWorkGroupSizeZ_EXT 128
MaxMeshViewCountEXT 4
MaxDualSourceDrawBuffersEXT 1
nonInductiveForLoops 1
whileLoops 1
doWhileLoops 1
generalUniformIndexing 1
generalAttributeMatrixVectorIndexing 1
generalVaryingIndexing 1
generalSamplerIndexing 1
generalVariableIndexing 1
generalConstantMatrixVectorIndexing 1
```

Am I missing something or are those limits not available through glslc (shaderc)?
If, so - is there a plan to support them?

**Comment by dneto0** [comment]
Good question.  They should be supported.
Previously NVIDIA has contributed the Shaderc/glslc support for things like raytracing.
