### ISSUE TITLE
shaderc::SpvModule should be renamed to shaderc::CompilationResult

### ISSUE THREAD

**Issue by dneto0** [google/shaderc#132]
The class is the result produced from compilation: status information plus the actual bits generated by the compiler.  Those bits are *usually* a SPIR-V module.  However, it can be something else, e.g. when doing the equivalent of -E (preprocess-only) or -M (target dependencies).

This change would go along with the (in-flight) rename of shaderc_spv_module to shaderc_compilation_result
https://github.com/google/shaderc/pull/126

**Comment by dekimir** [comment]
https://github.com/google/shaderc/pull/126/files#diff-13a2c8c8e3e8b2cf2d0483a74140ee9eL26
