### ISSUE TITLE
Warnings/errors aren't formatted properly for VS 2019 clickthrough

### ISSUE THREAD

**Issue by alecazam** [google/shaderc#1326]
glslc doesn't format errors for Visual Studio 2019.  This is a clang style format, that Xcode will jump to if an absolute path, but VS only jumps to the filename and not the line.  I thought I'd read that VS was now supporting clang-style formatting, but I'm on a recent VS install.

C:/Data/Shaders/Foo.frag:71: error: '' :  syntax error, unexpected RIGHT_PAREN, expecting LEFT_PAREN

This is what VS 2019 expects
C:/Data/Shaders/Foo.frag(71): error: '' :  syntax error, unexpected RIGHT_PAREN, expecting LEFT_PAREN

or this for line, column
C:/Data/Shaders/Foo.frag(71,5): error: '' :  syntax error, unexpected RIGHT_PAREN, expecting LEFT_PAREN

**Comment by dneto0** [comment]
Glslc emits file, line, and column information in a format consumed by Clang and GCC.
If VS is different then I suggest filing an enhancement request there.

**Comment by alecazam** [comment]
Wonderful. Seems like an quicker fix on your side to offer and option to format to VS style errors.  But here's the thread to Microsoft to try to fix this.  Jumping to the top line of a file isn't great for tracking and fixing errors across shader filles.

https://developercommunity.visualstudio.com/t/Visual-Studio-2019-not-honoring-line-num/10371387?moreInfo=true&viewtype=all
