### ISSUE TITLE
MSVC Static/Dynamic Runtime set incorrectly.

### ISSUE THREAD

**Issue by charles-lunarg** [google/shaderc#1337]
With CMake 3.15 and onwards using policy CMP0091, the -MD option is added. This is a problem because the [current code](https://github.com/google/shaderc/blame/4dc596ddc2702092c670e828745dc3e0338d83c1/CMakeLists.txt#L115) is looking for /MD, meaning that shaderc is being built with a dynamically linked CRT instead of the intended statically linked CRT.

The way to set the CRT with CMake 3.15 and above is `set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")`. This will change the default from dynamic CRT to static CRT.

I am willing to make a PR to fix this, but wanted to document that this is in fact an first.

**Comment by dneto0** [comment]
Thank you!

Now that we can rely on newer Cmake I bet there's all sorts of stuff that we can clean up. Please go ahead.  :-)
