### ISSUE TITLE
Gmock not found

### ISSUE THREAD

**Issue by xzores** [google/shaderc#1379]
I follow the build instruction for MSVC and i get the errors: 

```
-- No build type selected, default to Debug
-- Shaderc: build type is "Debug".
-- Configuring Shaderc to build tests.
-- Configuring Shaderc to build examples.
-- Configuring Shaderc to check copyrights.
-- asciidoctor was not found - no documentation will be generated
CMake Warning (dev) at cmake/setup_build.cmake:52 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  CMakeLists.txt:69 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/setup_build.cmake:17 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  CMakeLists.txt:94 (find_host_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at third_party/CMakeLists.txt:33 (message):
  gmock was not found - required for tests


-- Configuring incomplete, errors occurred!
```

**Comment by jiapei100** [comment]
Same issue here. 
In fact, `third_party` is empty, no **third_party** libraries at all.

**Comment by dj2** [comment]
If your third_party folder is empty you need to run the `utils/git-sync-deps` script to pull in the required dependencies.

**Comment by rubyFeedback** [comment]
Where can we find gmock? I am unable to locate it right now; google search redirected me to
abandoned projects (if "googlemock" is the same as "gmock"; that's another problem with
short names...).

**Comment by ben-clayton** [comment]
> Where can we find gmock?

As pointed out above:
> If your third_party folder is empty you need to run the `utils/git-sync-deps` script to pull in the required dependencies.

`gmock` is a target inside https://github.com/google/googletest. Yes, it's short for `googlemock`

All of `shaderc`'s dependencies can be found in https://github.com/google/shaderc/blob/main/DEPS, which is what the `utils/git-sync-deps` script uses.

**Comment by Dmitresso** [comment]
Faced same issue with Cygwin but installation [googletest](https://github.com/google/googletest) did not solve problem.
```
pkg-config --modversion gmock
1.15.2
```
