### ISSUE TITLE
shaderc_compile_into_spv cannot handle NULL input_file_name argument

### ISSUE THREAD

**Issue by httpdigest** [google/shaderc#201]
I think the input_file_name should only really be used when trying to deduce the shader kind from the file name. But when the shader kind is given as explicit argument, then the file name should not need to be given as well.
Currently, when calling shaderc_compile_into_spv with a NULL input_file_name argument, it crashes the process.
Where is not having a file name useful?
When using the shaderc_compile_into_spv with runtime-generated sources.

**Comment by dneto0** [comment]
The input file name is also used for generating error messages and for #include processing.
You can always supply an empty string.

**Comment by httpdigest** [comment]
Ah, you're right. Of course... the empty string. :)
Will use that then. Thanks!

**Comment by AWoloszyn** [comment]
I am going to re-open this. I think that even if you pass in nullptr we should not crash. Failing compilation and generating an error would be preferable.

**Comment by dneto0** [comment]
Fixed with https://github.com/google/shaderc/commit/c2dcb799e997779203da1207220cb1345582bcb7
