### ISSUE TITLE
Use libshaderc to assemble SPIR-V assembly into binary

### ISSUE THREAD

**Issue by httpdigest** [google/shaderc#205]
Currently, I only see a way to have GLSL source code and produce either preprocessed GLSL source, SPIR-V assembly or SPIR-V binary from it.
Is there a way to produce SPIR-V binary when having the SPIR-V assembly text?
Or do I have to just use SPIRV-Tools directly for that?

**Comment by antiagainst** [comment]
#80 is related to this issue.

**Comment by httpdigest** [comment]
But is SPIRV-Tools not already linked in? I mean, should it not already work, so it's just that the interface does not yet include that function?

**Comment by antiagainst** [comment]
Yeah, SPIRV-Tools is already linked in; just need to export that functionality in the interface.

**Comment by antiagainst** [comment]
The comments in #80 is a little out of date since that issue was created before SPIRV-Tools got linked in. Sorry for the confusion. :)

**Comment by httpdigest** [comment]
Alright. Thanks for the clarification. I would close this issue now, since it is basically identical to #80.
