### ISSUE TITLE
Hang if shader does not end with newline

### ISSUE THREAD

**Issue by hypernewbie** [google/shaderc#211]
If input shader does not end with newline, glslc.exe will hang.

**Comment by dekimir** [comment]
Sorry about that; it's a known issue with glslang's `TPpContext::tokenize()`.  It's being looked at...

**Comment by dekimir** [comment]
Actually, there's an upstream fix proposed already: https://github.com/KhronosGroup/glslang/pull/228

**Comment by hypernewbie** [comment]
Awesome. closing.
