### ISSUE TITLE
Cannot turn off tests

### ISSUE THREAD

**Issue by Lucretia** [google/shaderc#222]
Build still expects google test to be downloaded.

**Comment by dneto0** [comment]
Why do you want to turn off tests?  Is there an environment you're targeting that doesn't support googletest?

**Comment by Lucretia** [comment]
Yes, I've added it to my [Gentoo overlay](https://github.com/Lucretia/vulkan-overlay) and being able to not have to download all the external tools and turn off testing (unless specifically asked for) would be useful. I have ebuilds for the all dependencies bar googletests. Given what a small build this is, makes sense for users to be able to turn them off to save compile time.

**Comment by antiagainst** [comment]
Sorry for the late reply.

I've created PR #236 to address this.

**Comment by antiagainst** [comment]
Fixed via #236.
