### ISSUE TITLE
glslc fshader-stage evaluated before preprocessor macros

### ISSUE THREAD

**Issue by nallack** [google/shaderc#305]
I've currently been using macros with preprocessor conditionals around the shader entry points to combine multiple stages into a single glsl file. eg:
```
#if VERTEX_SHADER
void main() {...}
#endif
#if FRAGMENT_SHADER
void main() {...}
#endif
```

Using `-D` and `-fshader-stage` arguments, I always trigger the error:
`.glsl file encountered but no -fshader-stage specified ahead`

My current workaround has been to run glslc with `-E` to a intermediate file first, then process the preprocessed code with `-c` without any problems.

**Comment by dneto0** [comment]
You should use the #pragma shader_stage as in the following:

```
#version 450

#ifdef VERTEX
#pragma shader_stage(vertex)
#else
#pragma shader_stage(fragment)
#endif
void main() { }
```

Then compiling that two ways:
```
# this one compiles as vertex stage
glslc -c y.glsl -S -o -    -DVERTEX=1
# this compiles as fragment stage since that's the default.
glslc -c y.glsl -S -o -
```
