### ISSUE TITLE
CompilationResult begin end

### ISSUE THREAD

**Issue by nkyriazis** [google/shaderc#322]
I run into a problem feeding a CompilationResult<uint32_t> (acquired from shaderc::Compiler::CompileGlslToSpv) to vk::Device::createShaderModule (through vk::ShaderModuleCreateInfo). The size of the code was computed as the distance between begin and end. This distance needed to be multiplied by 4 (sizeof(uint32_t)) to correctly compute code size. This is a bit confusing if not incorrect.

**Comment by dneto0** [comment]
The CompilationResult class is templated over element type. In this case element type is uint32_t.  The begin and end iterators iterate over uint32_t.  So end() - begin() will be the number of uint32_t words.

The comment at the top of the class reinforces this. "The compiler output is stored as an array of elements and accessed via random access iterators provided by cbegin() and cend() ..."

The code works as intended.
