### ISSUE TITLE
shaderc_compile_into_spv_assembly doesn't disassemble `TimeAMD` properly

### ISSUE THREAD

**Issue by Jasper-Bekkers** [google/shaderc#325]
The following snippet compiles just fine with `shaderc_compile_into_spv`, but doesn't compile properly with `shaderc_compile_into_spv_assembly`.

It fails with this internal error:

> shaderc: internal error: compilation succeeded but failed to disassemble: 23: Invalid extended instruction import 'SPV_AMD_gcn_shader'

```
#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
#extension GL_ARB_gpu_shader_int64 : enable
#extension GL_AMD_gcn_shader : enable

void main() 
{
	uint64_t v = timeAMD();
}
```

Looks like some minor support for it is still missing.

**Comment by dneto0** [comment]
Understood.   Shaderc relies on SPIRV-Tools for this, and SPIRV-Tools does not have grammar files for the  AMD extensions.

**Comment by Jasper-Bekkers** [comment]
Should I file this issue on SPIRV-Tools instead or will you?

**Comment by dneto0** [comment]
Please file it against SPIRV-Tools.   It shows we have users, and might get attention more quickly  :-)

**Comment by Jasper-Bekkers** [comment]
I think this issue is resolved since it's resolved in SPIRV-Tools
