### ISSUE TITLE
glslc writes bad dependency file if `-o -`

### ISSUE THREAD

**Issue by chadversary** [google/shaderc#327]
If glslc is given option '-o -' and one of the -M* dependency
options, then it wrote an incorrect dependency file. For example:

    $ glslc -MD -S -o - a.glsl | sed ...
    $ ls
    -.d a.glsl
    $ cat ./-.d
    -: a.glsl

 It doesn't make sense to write a dependency file when the compilation
  output is stdout. So glslc should catch this error when parsing the command line flags.j

**Comment by chadversary** [comment]
More investigation. I think glslc should allow `-MD` with `-o -`, but only when `-MT <depfile>` is also given.

**Comment by chadversary** [comment]
NEVERMIND. glslc correctly behaves the same as gcc when given `-o -` with `-M*` options. Here is a test that demonstrates the gcc behavior.

```
#!/bin/bash

setup() {
    # Clean!
    rm -f hello* ./-*

    cat >hello.c <<-EOF
	#include "hello.h"
	
	int main(void) {
	    hello();
	    return 0;
	}
	EOF

    cat >hello.h <<-EOF
	#include <stdio.h>
	
	static inline void
	hello(void) {
	    printf("hello!\n");
	}
	EOF
}

start_test() {
    test_name="$1"
    echo "test $test_name ..."
}

pass() {
    echo "test $test_name ... pass"
}

fail() {
    echo "test $test_name ... fail"
    exit 1
}

testA() {
    start_test "A"
    setup || fail
    gcc -S -o - -MMD hello.c >/dev/null || fail
    [[ -f ./-.d ]] || fail
    [[ $(cat ./-.d) = "-: hello.c hello.h" ]] || fail
    pass
}

testB() {
    start_test "B"
    setup || fail
    gcc -S -o - -MMD -MF hello.o.d -MT hello.o hello.c >/dev/null || fail
    [[ -f hello.o.d ]] || fail
    [[ $(cat hello.o.d) = "hello.o: hello.c hello.h" ]] || fail
    pass
}

testA
testB
```

**Comment by dneto0** [comment]
My favourite kind of bug.  :-)

Thanks for the explanation.   Yes, we used gcc as the model for this feature.  I'm glad we are close enough to it in behaviour.
