### ISSUE TITLE
New file structure breaks Vulkan API Samples build

### ISSUE THREAD

**Issue by jpryne** [google/shaderc#333]
Error:error: 'C:/Users/Jack/AppData/Local/Android/sdk/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a', needed by '../../../../build/intermediates/cmake/debug/obj/x86/libvulkan_sample.so', missing and no known rule to make it

**Comment by dneto0** [comment]
The NDK does not ship with binaries for the shader utiltiies. (But we're considering doing so.)

Did you follow the instructions to build the shader libraries first? https://developer.android.com/ndk/guides/graphics/shader-compilers.html#integrating 

Also, I don't know what "new file structure" you're referring to.

**Comment by jpryne** [comment]
Perhaps I misunderstood. Thanks for the guidance!
