### ISSUE TITLE
CMake Build use GNUInstallDirs

### ISSUE THREAD

**Issue by d3x0r** [google/shaderc#353]
Should use GNUInstallDirs module to get proper output names for install.  Not all systems have 'lib' as the target for libraries, but sometimes use lib64, and this library takes care of the target names.

https://cmake.org/cmake/help/v3.4/module/GNUInstallDirs.html

include( GNUInstallDirs )
and then use ${CMAKE_INSTALL_LIBDIR} to get the correct name of library to install to. (lib64 vs lib)
and ${CMAKE_INSTALL_BINDIR} for target binary directory (although that seems to always be 'bin' anyway)

**Comment by dneto0** [comment]
Fixed on master with squash/rebase of your PR:  see commit e27569f020
