### ISSUE TITLE
Compilation for DirectX 12?

### ISSUE THREAD

**Issue by capitalknew** [google/shaderc#355]
Hello. Need support for DirectX 12. I not found any mentions about compilation target to DirectX 12 (DXIL). Source language - GLSL. (i.e. compile GLSL450 with potentially compatible extensions for DirectX 12)
It possible? If not - will be? And how?

**Comment by dneto0** [comment]
I don't know of any work to do this.  We will not work on this in the Shaderc project.

The closest I can think of is a compilation to the Vulkan form of SPIR-V via Glslang or Shaderc, and then using experimental support in SPIRV-Cross to generate HLSL (https://github.com/KhronosGroup/SPIRV-Cross).

A less likely choice is to use ANGLE to do the GL to DirectX translation for you.  But that supports a much lower level of GLSL (GLSL ES 2?).  Also, I don't know if they target DirectX 12, so I don't know if they have a DXIL backend.

**Comment by capitalknew** [comment]
But possible to convert glsl450 for GLES?

**Comment by dneto0** [comment]
In general GLSL targets desktop GPUs, and GL ES targets mobile GPUs which tend to be less capable.  So GLSL 450 generally has a lot of features that don't exist on mobile GPUs and so aren't reflected in GL ES.    So you have to handle translation on a case-by-case basis.   I don't think a general downgrading of GLSL 450 to ESSL (the confusing name for GLSL for OpenGL ES) is even possible.

**Comment by capitalknew** [comment]
Also, will support OpenGL SPIRV from HLSL?

**Comment by dneto0** [comment]
We depend on Glslang for the core compilation technology.  All these questions and requests should go to KhronosGroup/glslang
