### ISSUE TITLE
What does 'non-opaque uniforms outside a block' mean?

### ISSUE THREAD

**Issue by linuxaged** [google/shaderc#357]
when compiling my 310es shader to SPIR-V get the error:

    error: 'non-opaque uniforms outside a block' : not allowed when using GLSL for Vulkan

what does it mean?

My shaders:

        // vertex
        #version 310 es
        #extension GL_EXT_shader_io_blocks : enable
        #extension GL_ARB_enhanced_layouts : enable
        precision highp float;
        precision highp int;
        layout( std140, binding = 0 ) uniform viewProjectionUniformBuffer
        {
                layout( offset =   0 ) mat4 u_viewMatrix;
                layout( offset =  64 ) mat4 u_viewInverseMatrix;
                layout( offset = 128 ) mat4 u_projectionMatrix;
                layout( offset = 192 ) mat4 u_projectionInverseMatrix;
        };
        layout( location = 1 ) uniform mat4 u_modelMatrix;
        layout( location = 2 ) uniform mat4 u_modelInverseMatrix;
        out gl_PerVertex { vec4 gl_Position; };
        layout( location = 1 ) in vec3 a_normal;
        layout( location = 0 ) out vec3 v_normal;
        layout( location = 0 ) in vec3 a_position;
        layout( location = 1 ) out vec3 v_position;
        layout( location = 2 ) in vec2 a_texcoord0;
        layout( location = 2 ) out vec2 v_texcoord0;
        void main ( void )
        {
                vec4 pos = u_viewMatrix * u_modelMatrix * vec4 ( a_position, 1.0 );
                v_normal = transpose( mat3( u_viewInverseMatrix ) ) * transpose( mat3( u_modelInverseMatrix ) ) * a_normal;
                v_texcoord0 = a_texcoord0;
                gl_Position = u_projectionMatrix * pos;
        }

        // fragment
        #version 310 es
        #extension GL_ARB_enhanced_layouts : enable
        precision highp float;
        precision highp int;
        layout( location = 0 ) out vec4 fragColor;
        layout( location = 0 ) uniform sampler2D u_diffuse;
        layout( location = 3 ) uniform vec4 u_emission;
        layout( location = 0 ) in vec3 v_normal;
        layout( location = 1 ) in vec3 v_position;
        layout( location = 2 ) in vec2 v_texcoord0;
        layout( location = 4 ) uniform float u_transparency;
        void main ( void )
        {
                vec4 color = vec4 ( 0., 0., 0., 0. );
                vec4 diffuse = vec4 ( 0., 0., 0., 1. );
                vec4 emission;
                diffuse = texture ( u_diffuse, v_texcoord0 );
                emission = u_emission;
                color.xyz += diffuse.xyz;
                color.xyz += emission.xyz;
                color = vec4 ( color.rgb * diffuse.a, diffuse.a * u_transparency );
                fragColor = color;
        }

**Comment by antiagainst** [comment]
Hi @linuxaged,

Sorry for the late reply.

To use GLSL as the a high-level language for the Vulkan API, you'll need to make sure that the code follows [GL_KHR_vulkan_glsl](https://www.khronos.org/registry/vulkan/specs/misc/GL_KHR_vulkan_glsl.txt). In the "Overview" section,

> The following features are removed:
>       * default uniforms (uniform variables not inside a uniform block), except for opaque types

So, you cannot have input/output variables like `u_modelMatrix` as a standalone, they should be grouped into a uniform block I think.
