### ISSUE TITLE
Incompatibility with libVulkan_core_validation on Android

### ISSUE THREAD

**Issue by tipoc** [google/shaderc#367]
I had a problem with compatibility with validation layers on Android. It described here:

https://stackoverflow.com/questions/45924342/shaderc-crashes-on-calling-glsl-to-spv-assembly-on-android

Is it really incompatible at the moment? If so does it going to be compatible in future?
Or did I maybe something wrong and the validation layers actually somehow can be used with shaderc on Android?

**Comment by dneto0** [comment]
Sorry for this trouble.

I believe the prebuilt Android layers are very much out of date.   I understand that in theory you could compile the layers yourself from fresher sources, and that should fix the problem.  I expect the NDK will be updated soon with a refreshed set of binary layers.

**Comment by tipoc** [comment]
Yes, indeed. After building and using latest source of validation layers everything works. Thank you very much!
