### ISSUE TITLE
API call to determine supported GLSL version?

### ISSUE THREAD

**Issue by haasn** [google/shaderc#371]
I have a codebase that enables and disables GLSL features based on the supported GLSL version by the compiler. Unfortunately, it doesn't seem that `libshaderc` exports any information about this, so the best I can do is hard-code “glsl_version = 450” for libshaderc. But this seems brittle and non-future proof.

Would it be reasonable to add an API call to determine the supported GLSL version for a given target (e.g. SPIR-V 1.0)?

**Comment by dneto0** [comment]
We are strongly dependent on Glslang and its support is a moving target.  It doesn't have such an API and it would be even more fragile if Shaderc invented one.

**Comment by haasn** [comment]
Well, as it stands, it has to be hard-coded somewhere: which is currently “in my application”. But in either case, it seems like this bug report would be more appropriate for glslang then.
