### ISSUE TITLE
API call to disassemble already-compiled shader

### ISSUE THREAD

**Issue by haasn** [google/shaderc#372]
For debugging purposes it can be useful to disassemble the generated SPIR-V. Right now, in my debug code path I essentialy compile the shader twice - once to get a SPIR-V binary and once to get a SPIR-V assembly.

It would be useful if you can package up the dedicated “SPIR-V disassembly” functions provided by e.g. “spirv-dis” in such a way that I can run it either on a compilation result or on an arbitrary SPIR-V binary and get a disassembly as a result.

**Comment by dneto0** [comment]
You're looking for:

```
// Decodes the given SPIR-V binary representation to its assembly text. The
// word_count parameter specifies the number of words for binary. The options
// parameter is a bit field of spv_binary_to_text_options_t. Decoded text will
// be stored into *text. Any error will be written into *diagnostic if
// diagnostic is non-null.
spv_result_t spvBinaryToText(const spv_const_context context,
                             const uint32_t* binary, const size_t word_count,
                             const uint32_t options, spv_text* text,
                             spv_diagnostic* diagnostic);
```
See https://github.com/KhronosGroup/SPIRV-Tools/blob/master/include/spirv-tools/libspirv.h#L443

Alternately, spvootls::SpirvTools::Disassemble:
https://github.com/KhronosGroup/SPIRV-Tools/blob/master/include/spirv-tools/libspirv.hpp#L100

**Comment by haasn** [comment]
Seems like the function I'm looking for; although unfortunately it's not re-exported by libshaderc_shared.so so I believe I'll continue using the double-compile trick for now.
