### ISSUE TITLE
shaderc.h checks for WIN32, not _WIN32

### ISSUE THREAD

**Issue by dylanede** [google/shaderc#383]
When building with MSVC2017 via CMake, I get errors in shaderc.h due to WIN32 not being defined (and so SHADERC_EXPORT ends up having the wrong definition for the platform). Apparently the correct thing to check for is _WIN32, i.e. change

```C
    #if defined(WIN32)
```

to

```C
    #if defined(_WIN32)
```

**Comment by AWoloszyn** [comment]
Thanks for the report. Not sure why I have not seen this in 2017, but it is definitely incorrect as it stands.

**Comment by dylanede** [comment]
Should this be closed since that fix was merged?

**Comment by antiagainst** [comment]
Yep.
