### ISSUE TITLE
Support for `#pragma once` in includes

### ISSUE THREAD

**Issue by dylanede** [google/shaderc#385]
Without `#pragma once`, include guards must be used, which are quite error prone.

**Comment by dneto0** [comment]
We will not add `#pragma once`

We (mostly) follow the Google style guide.  In the section on Windows code (https://google.github.io/styleguide/cppguide.html#Windows_Code)
it says:

> Windows programmers have developed their own set of coding conventions, mainly derived from the conventions in Windows headers and other Microsoft code. We want to make it easy for anyone to understand your code, so we have a single set of guidelines for everyone writing C++ on any platform.

Adding the pragma would open the door to incompatible behaviour with other compilers.
