### ISSUE TITLE
Add command-line option to select SPIR-V generation mode (Vulkan or OpenGL)

### ISSUE THREAD

**Issue by antiagainst** [google/shaderc#40]
glslang [has two command-line options](https://github.com/KhronosGroup/glslang/blob/master/StandAlone/StandAlone.cpp#L954-L958) to generate SPIR-V:
* `-V`: under Vulkan semantics
* `-G`: under OpenGL semantics

shaderc should also support some kind of command-line option to select the mode.

**Comment by dneto0** [comment]
We already have "-x glsl".  Normally language dialect is chosen with "-std=<name>"  but shaderc already has "-std=310es" for example.  Let's keep this open until Vulkan ships then we see how it expresses version numbers.

**Comment by antiagainst** [comment]
Already done by [`--target-env=`](https://github.com/google/shaderc/tree/master/glslc#423---target-env).

**Comment by capitalknew** [comment]
But anyways not possible to define version of SPIR-V (1.0, 1.1, 1.2).
