### ISSUE TITLE
use SPIRV-Tools HLSL legalization recipe instead of our own

### ISSUE THREAD

**Issue by dneto0** [google/shaderc#435]
See libshaderc_util/src/compiler.cc.  It has its own recipe for HLSL legalization.  Instead we should delegate the recipe to spvtools::Optimizer::RegisterLegalizationPasses

**Comment by dneto0** [comment]
See #380

**Comment by antiagainst** [comment]
#447 to fix this.

**Comment by antiagainst** [comment]
Done via #447.
