### ISSUE TITLE
API for setting target env should allow switching between Vulkan 1.0 an Vulkan 1.1

### ISSUE THREAD

**Issue by dneto0** [google/shaderc#442]

**Comment by dneto0** [comment]
The uint32_t version number should have same structure as the Vulkan API word (shift by 22 bits, shift by 12 bits).  This also matches Glslang's version numbering for the target API env.  (GitLab Glslang issue 49)

**Comment by dgkoch** [comment]
I guess this can be closed due to #445 (c9931580dbf84657796e83e61bb682df51fd72ee)?

**Comment by antiagainst** [comment]
Yes. Thanks for the reminder!

**Comment by dgkoch** [comment]
Thanks BTW!  It appears to work as advertised (I'm already testing the change in my workflow).

**Comment by antiagainst** [comment]
That's very glad to hear! :D
