### ISSUE TITLE
libshaderc doesn't use many optimization passes

### ISSUE THREAD

**Issue by chrisvarns** [google/shaderc#448]
Hi,

Part question part issue report, I noticed that in `Compiler::SetOptimizationLevel`, there are relatively few optimization passes enabled compared to what is set by either `spvtools::Optimizer::RegisterPerformancePasses` (granted there is no option for performance in shaderc right now anyway) or `spvtools::Optimizer::RegisterSizePasses`. Is this intended?

Thanks,
Chris

**Comment by antiagainst** [comment]
Hi @chrisvarns, thanks for reporting!

We've noticed this and I've https://github.com/google/shaderc/pull/447 to fix it.

**Comment by chrisvarns** [comment]
oh wow, less than a day ago! How weird. I'll check out the PR and see if its similar to what I was about to PR :P

**Comment by chrisvarns** [comment]
It is identical to what I was going to do to the spirv wrapper, but missing the `OptimizationLevel::Performance` I was going to add to the shaderc API. Should I make a PR for that?

**Comment by antiagainst** [comment]
I've uploaded https://github.com/google/shaderc/pull/447/commits/33ba871a3fc28c74a93df6d979863530f9d17112 that should address your needs. PTAL ;-P

**Comment by chrisvarns** [comment]
Nice thank you 👍 I will pull and give it a go
