### ISSUE TITLE
Windows dll's don't get installed

### ISSUE THREAD

**Issue by chrisvarns** [google/shaderc#449]
If I attempt to "install" with `ninja install`, the libs get copied but not the dll's.

**Comment by dneto0** [comment]
shaderc_shared is listed as an install target: https://github.com/google/shaderc/blob/master/libshaderc/CMakeLists.txt#L33 

I'm less experienced with CMake on Windows DLLs.  He @AWoloszyn  or @antiagainst can you take a look?

**Comment by AWoloszyn** [comment]
We should also be adding
```
RUNTIME DESTINATOIN ${CMAKE_INSTALL_BINDIR}
```
To that line.
The .dll is neither a Library or an Archive.
I can get a MR together to fix this. Hopefully that doesn't break the other platforms.

**Comment by dneto0** [comment]
Indeed, install directives inside SPIRV-Tools have that line.  Thanks!

**Comment by AWoloszyn** [comment]
Fixed by #451
