### ISSUE TITLE
Travis-CI OSX builds failing due to PyPI failure to download

### ISSUE THREAD

**Issue by dneto0** [google/shaderc#454]
Seems related to https://mail.python.org/pipermail/distutils-sig/2017-October/031712.html 

That page was found from https://community.plone.org/t/buildout-not-working-couldnt-find-index-page-for-couldnt-find-a-distribution-disabling-non-https-access-to-apis-on-pypi/5069/9

**Comment by antiagainst** [comment]
Fixed via #461
