### ISSUE TITLE
Glslang tests fail because its HLSL legalization is disabled

### ISSUE THREAD

**Issue by dneto0** [google/shaderc#459]
Commit https://github.com/google/shaderc/commit/2a0f3a3e348072ad6a9e53874188146b895705ba changed the order of project inclusion so that Glslang comes before SPIRV-Tools.  The idea was to have Shaderc control the optimization recipes rather than the ones in Glslang.

However, that means Glslang's self-tests fail because the "compoundsuffix.frag.hlsl" compilation no longer does HLSL legalization.  That causes a difference in output, which fails the tests.

So we have to reorder the includes, but always force compilation via Shaderc to *disable* HLSL legalization. 

Assigning to @antiagainst to fix.

This is blocking all future changes, such as #458

**Comment by dneto0** [comment]
In theory, this is also a bug in Glslang because its own tests fail if SPIRV-Tools is not available or configured.  But Shaderc ought to be resilient to however the components are combined.

**Comment by johnkslang** [comment]
The glslang test does not need legalization. I will turn that off in glslang.

**Comment by johnkslang** [comment]
This is fixed now in glslang: https://github.com/KhronosGroup/glslang/commit/ecbd056b75cdd765428d2d4f46850f3b92a24941, which should use -Od for its HLSL tests in `runtests`.

**Comment by antiagainst** [comment]
Thanks, John!

I've also submitted #460 to have SPIRV-Tools linked into Glslang.
