### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by polyzen** [google/shaderc#464]
Versioned source tarballs (though in this case auto-generated by GitHub) are quite useful for package maintainers.

**Comment by linuxturtle** [comment]
Also quite useful for *anyone* who wants to version/recreate a particular build.

**Comment by dneto0** [comment]
I haven't forgotten.

**Comment by linuxturtle** [comment]
So, it looks like you've tagged the master branch, not known-good.  How does one use this tag to create a reproducible build?  Am I missing something?

**Comment by linuxturtle** [comment]
I.e. it seems like the release tag should be on the known-good branch, once it's updated to reference the commit in master where you updated the changelog.  Otherwise, there's no way to build a release in a reproducible way (with known/specified commits of third_party software).

**Comment by linuxturtle** [comment]
Upon further reflection, and updating my debian package, please ignore my last two comments :laughing:  The tag is right where it should be to make tag-based package versioning meaningful.  Package versioning based on a known-good tag would not be meaningful, and if I want a reproducible build, I can tag known-good in my fork, or just keep track of the commit ID.  Sorry for the wasted bandwidth :)

**Comment by polyzen** [comment]
@dneto0, thank you.

**Comment by dneto0** [comment]
Thanks for your thoughtful feedback and patience on this one, everyone.
