### ISSUE TITLE
Use Kokoro bots instead of AppVeyor and Travis-CI

### ISSUE THREAD

**Issue by dneto0** [google/shaderc#467]
Kokoro is more responsive than Travis-CI and AppVeyor, probably because we're on the free tier of both those services. We can afford the time to cover more cases with Kokoro.

Thanks to @ehsannas for setting up Kokoro bots, and to prove that the logs can be made public, e.g. see
https://github.com/google/shaderc/pull/466 

Last items to switch over fully:

- Cover all VisualStudio cases that AppVeyor covers:
   - [x] VS 2013 Release build
   - [x] VS 2017 Release build
   - [x] VS 2017 Debug build
   - [x] Remove VS 2015 Debug build. (Keep the release build)
- Update badges on the README:
  - [x]  Kokoro bot result badges on the README should point to the logs for the latest run. 
  - [x] Remove the Travis and AppVeyor badges
  - [x] Turn off the AppVeyor bots
  - [x] Turn off the Travis-CI bots

**Comment by ehsannas** [comment]
Windows bots updated via #468

**Comment by antiagainst** [comment]
This is done as of https://github.com/google/shaderc/pull/490

**Comment by abourget** [comment]
What's kokoro?
