### ISSUE TITLE
ctests don't work with Python3

### ISSUE THREAD

**Issue by dneto0** [google/shaderc#474]
Example error:

shaderc/glslc/glslc --help                                                                                │
a bytes-like object is required, not 'str'

**Comment by dneto0** [comment]
Is this something with file reading?  The error message is not very helpful

**Comment by dneto0** [comment]
This is beyond me.  Can you help @antiagainst  ?

**Comment by antiagainst** [comment]
Sure, I'll take a look at this issue.

**Comment by s-perron** [comment]
I'll take this issue.  Since python2 will be sunset at the end of the year, we should make sure shaderc and all of the subprojects work with python3.

**Comment by s-perron** [comment]
https://github.com/google/shaderc/pull/569 should fix the shaderc scripts.

The spirv-tools scripts will be fixed by https://github.com/KhronosGroup/SPIRV-Tools/pull/2426.  Other components do not seem to have any problems.
