### ISSUE TITLE
Optimisation parameters are not documented in help

### ISSUE THREAD

**Issue by baldurk** [google/shaderc#478]
The help string doesn't mention `-O`, `-Os` or `-O0`.

It might also be helpful for `-O1` to work as an alias for 'enable optimisation', even if there aren't `-O2` and `-O3`. I tried to figure out the flags by experimentation before looking at the source, and I didn't guess the bare `-O`.

**Comment by dneto0** [comment]
Whoops. Sorry for that oversight.

glslc aims to be as similar to Clang and GCC as possible on the command line.  So -O exists just like it exists in those compilers.

**Comment by antiagainst** [comment]
I documented it in the online manual: https://github.com/google/shaderc/tree/master/glslc#452--o0--os but neglected the help message. Fixed with #480.
