### ISSUE TITLE
Newer SPIRV-Tools breaks hlsl compilation

### ISSUE THREAD

**Issue by baldurk** [google/shaderc#499]
SPIRV-Tools recently started running the validator on inputs before optimisation, see KhronosGroup/SPIRV-Tools#1799.

The validator runs with default options, which means that even with implied hlsl-offsets the validator uses glsl rules which disallows struct layouts like `cbuffer foo { float a; float3 b; }`.

The fix I think is in `SpirvToolsOptimize`, to add an explicit `spvtools::OptimizerOptions`. That would either let you configure validation to match the environment, or better yet just disable the validator. IMO the validator should **not** run by default on an internal pass since that's going to slow down compilation for everyone in a place the "shouldn't" have validation errors. Especially since it seems it was only added for the benefit of some fuzzing process that could opt-in to run validation itself before passing to spirv-opt.

The same problem happen with GLSL with opt-in hlsl-offsets - the option_dash_fhlsl_offsets.py test would hit this if it enabled optimisation, hlsl only hits it because of the required legalisation pass.

This affects the glslc in SDK 1.1.85.0.

**Comment by dj2** [comment]
The spv_optimizer_options has a method : spvOptimizerOptionsSetRunValidator where you can disable the validator when running the optimizer. You can also set the validator options by calling: spvOptimizerOptionsSetValidatorOptions.

Just note, the optimizer isn't safe to run if there is invalid SPIRV. It will assert.

**Comment by dneto0** [comment]
I agree the compiler should work out-of-the-box.  For HLSL compilation validation should be turned off or tuned to avoid the things we know the legalization steps will be working around.  When offsets are requested to be relaxed, those validation rules should be tuned down as well.
