### ISSUE TITLE
Possibility of dual-licensing under something compatible with (L)GPLv2?

### ISSUE THREAD

**Issue by haasn** [google/shaderc#509]
Currently, shaderc cannot be used with an (L)GPLv2 project due to incompatibilities between the Apache license. The only work-around is relicensing to LGPLv3 which can cause integration issues in projects that refuse to release under LGPLv3.

Would you be interested in relicensing or dual licensing shaderc if somebody asks you nicely enough? Or is this impossible if, as I fear, the use of the Apache strategy a deliberate ploy to Google to prevent users from using it on the Apple store? (AKA "no freedom allowed" zone)?

**Comment by dj2** [comment]
It is my understanding that the Apache license is compatible with the App Store. Can you please point me to where it says the Apache license is not compatible?

**Comment by haasn** [comment]
@dj2 To clarify: The issue is when you try combining shaderc with other pieces of free software that are GPLv2 licensed. GPLv2 is allowed on the App Store, but as soon as a GPLv2 project tries using shaderc, it's no longer allowed.

So from the perspective of a project like VLC Media Player, that effectively translates to "it would no longer be allowed on the app store, therefore we cannot use it (shaderc)", and I am put into the unfortunate position of having to drop shaderc in favor of writing my own shims to (badly) wrap glslang.

**Comment by haasn** [comment]
**Update**: It appears I was mistaken. GPLv2 is *not* allowed on the Apple App Store either, so the Apache2 + GPLv2 issue doesn't exist. It only affects, for example, the Windows App Store (which forbids GPLv3). That lessens the importance of this issue considerably - although it doesn't change the fact that VLC is unwilling to make libvlc be GPLv3.

**Comment by haasn** [comment]
It does, however, appear as though LGPLv2 is allowed on the app store (while GPLv2 is not), and LGPLv2+Apache2 = LGPLv3, which is again not allowed on the app store. So the issue stands that shaderc cannot be used together with an LGPLv2 project on the app store since their combination is LGPLv3 which has the anti-tivo clause.

**Comment by haasn** [comment]
Pretty much. I think you can add an extra clause to the apache license to make it compatible with (L)GPLv2 as a special exception.

**Comment by dneto0** [comment]
I am not a lawyer, and I don't make up our policies for open source.  We develop Shaderc out in the open with clear terms in the hope that it is useful.

The issues you are encountering are larger than Shaderc, and are not going to be resolved here in an issue.  I wish you the best of luck in making forward progress.
