### ISSUE TITLE
Shaderc adding spirv-headers subdirectory

### ISSUE THREAD

**Issue by dj2** [google/shaderc#512]
In the third_party CMakeList.txt file the spirv-headers is added with an add_subdirectory() call. These doesn't seem useful as spirv-headers doesn't really do anything. It sets up some install targets and creates a couple of strange example libraries. (Those example libraries are generating linker warnings locally as they seem to be empty).

Can we remove the add_subdirectory for spirv-headers?

**Comment by dneto0** [comment]
Doing add_subdirectory has a useful side-effect of setting SPIRV-Headers_SOURCE_DIR which is sometimes used in the containing project.

**Comment by dj2** [comment]
This was fixed the other way by making SPIRV-Headers compilation of the examples conditional and turning it off in Shaderc.
