### ISSUE TITLE
Using shader types from NV_EXTENSIONS

### ISSUE THREAD

**Issue by SirKnightTG** [google/shaderc#521]
I'm using a freshly built shaderc_shared.dll in my app and I'm trying to compile a task shader. I thought NV_EXTENSIONS are enabled in the shaderc build by default, but when I pass shaderc_glsl_task_shader to CompileGlslToSpv() I get back an error that I'm using an invalid stage. I also tried one of the ray tracing shader types just for kicks and get the same error.

Is there a certain option that needs to be passed to CompileOptions I'm missing? I tried adding AddMacroDefinition("NV_EXTENSIONS", "1") but I still get the same error. I built shaderc according to the instructions for cmake and Visual Studio (I have 2017).

My GPU is a 2080 Ti and OS is Windows 10.

**Comment by dneto0** [comment]
Have you turned the extension on in the shader?  You need to include this line:

      #extension GL_NV_mesh_shader : enable

I just compiled the shader at https://github.com/KhronosGroup/glslang/blob/master/Test/spv.meshTaskShader.task 
using this command line:

 glslc -c spv.meshTaskShader.task -o a.spv

and it worked fine.

**Comment by dneto0** [comment]
Cc' @dgkoch in case other advice is needed.

**Comment by SirKnightTG** [comment]
Yes the #extension line is there.

What's strange is compiling it offline using glslc works, the problem only shows up when using the shaderc API (CompileGlslToSpv()) to compile.

**Comment by SirKnightTG** [comment]
Ok I figured out the problem. Turns out I had a post build step that copies DLLs into the right places so the app will run and there was an issue of me not loading the DLL I thought I was. I had a stale one being loaded that didn't have the NV_EXTENSION support. Doh!
