### ISSUE TITLE
add libshaderc_spvc and spvc tool

### ISSUE THREAD

**Issue by fjhenigman** [google/shaderc#526]
libshaderc_spvc will call the spirv-tools validator then any of the spirv-cross compilers.
spvc will be a command line tool, similar to the spirv-cross command line compiler.
Later we'll also avoid the spirv-cross parser by constructing ourselves the data structures accepted by the compiler.

**Comment by zoddicus** [comment]
I believe as described the initial implementation of the library and command line tool is done. Outstanding work tasks relate to iterating on the existing tool to make it production ready.
