### ISSUE TITLE
MSYS2/MinGW, GCC: suggest parentheses for sameStructType (glslang)

### ISSUE THREAD

**Issue by LigH-de** [google/shaderc#535]
Trying to compile [google/shaderc](https://github.com/google/shaderc) (which uses spirv-tools) in [MABS](https://github.com/jb-alvarado/media-autobuild_suite).

Default for GCC in MSYS2/MinGW is treating warnings as errors. This causes an error for an ambiguous boolean sequence. Details reported to [KhronosGroup/glslang issue 1650](https://github.com/KhronosGroup/glslang/issues/1650).

**Comment by dneto0** [comment]
This was fixed upstream already.
