### ISSUE TITLE
libshader_spvc should compact ids before invoking spirv-cross

### ISSUE THREAD

**Issue by zoddicus** [google/shaderc#536]
Due to how spirv-cross handles ids internally, large id bounds cause large memory allocations and performance issue, see https://github.com/KhronosGroup/SPIRV-Cross/issues/781 for details.

In the case that the ids are actually sparse, compacting them and minimizing the bound can have significant performance benefits. spvc should pass inputs to spirv-cross through spirv-opt with --compact-ids, which will rewrite it to have compact ids and minimize the bound.

**Comment by dneto0** [comment]
If spirv-cross has resolved the scaling issue then maybe this is no longer needed?

**Comment by zoddicus** [comment]
This is fixed by #631
