### ISSUE TITLE
kokoro build bots: Need to cover the ndk-build case

### ISSUE THREAD

**Issue by dneto0** [google/shaderc#539]
The android cross-compiles currently use the CMake mechanism. That means the bots are not covering the ndk-build flow, and the issue addressed in https://github.com/google/shaderc/pull/538 fell through the cracks.

**Comment by fjhenigman** [comment]
I can try to fix up kokoro/ndk-build
- scripts need updating
- missing continuous_google.cfg
- missing presubmit_{khronos,google}.cfg

I don't know how to send CLs to google3 but @ehsannas does.

**Comment by dneto0** [comment]
Fixed by #540
