### ISSUE TITLE
spirv-cross in known-good?

### ISSUE THREAD

**Issue by greg-lunarg** [google/shaderc#557]
It seems that spirv-cross has been added to shaderc, yet there does not seem to be an entry for spirv-cross in known-good.json. Shouldn't there be one? We are having build problems with newer shaderc versions complaining about missing spirv-cross files.

And as long as you are editing known-good.json, can you bump up the glslang version as well, to something that includes 8dff52?

**Comment by dneto0** [comment]
@dj2 : i've been updating the known-good branch when I've verified that the NDK build and test flows also work.  That's not covered by the DEPS roll criteria, I don't think.

@greg-lunarg :  The requirement of spirv-cross was not properly guarded at first.
If you pick up shaderc at 6ff17fe32 or later then I think your compiles will start working again.
Sorry about the hiccups.

**Comment by fjhenigman** [comment]
> @dneto0 We tried [6ff17fe](https://github.com/google/shaderc/commit/6ff17fe32fd2e0b6bc1890befaf036d526b24540) yesterday and were still getting spirv-cross-related build failures :(

The spirv-cross stuff should be disabled by default.  If you describe the failure I'll try to help.

**Comment by greg-lunarg** [comment]
Essentially, build shaderc at 6ff17fe with no spirv-cross files in third-party/. That works for you?

**Comment by greg-lunarg** [comment]
On Android?

**Comment by greg-lunarg** [comment]
Thanks, but it looks like the *real* problem is that the Android build/CI process for shaderc in the Vulkan Validation Layers has fallen behind given these recent changes to shaderc. I push ahead in that area.

**Comment by fjhenigman** [comment]
We didn't want any of recent changes to shaderc to break anything.  Though we had some temporary regressions, the latest revision is good as far as we know.  Please reopen this bug if that is not the case.  Thanks.
