### ISSUE TITLE
New known_good?

### ISSUE THREAD

**Issue by greg-lunarg** [google/shaderc#560]
Sorry for the extra rev, but would it be possible to get the known-good for shaderc updated to the following?:

glslang
8dff52509e5c73818d70ea5386886b6cb908962f 

spirv-tools
e2279da7148d19bd21c6d47ffc96ee4176f43dba
(essentially, the version in the above glslang's known-good)

We are trying to resolve Android build issues for Vulkan-ValidationLayers PR (requested by some Google folks) and we need this done as the first step.

Here is the related PR:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/638

**Comment by greg-lunarg** [comment]
@fjhenigman @dj2 Can either of you help with this?

**Comment by dneto0** [comment]
I ran into problems with compilation of parameterized googletests.  I think I have to post a fix to shderc and glslang

**Comment by dneto0** [comment]
Shaderc PR https://github.com/google/shaderc/pull/561

**Comment by dneto0** [comment]
Correction: Glslang is just fine. I was accidentally stuck on an old version of its code.

**Comment by dneto0** [comment]
#561 has landed.
Also need https://github.com/google/shaderc/pull/563 to make the spvc part of Shaderc optional and off by default in the ndk-build flow because the Android NDK build does not have the SPIRV-Cross.

**Comment by dneto0** [comment]
#563 has landed.

I've updated the known-good branch, after verifying in the NDK build.
See https://github.com/google/shaderc/commit/00d32b05d78fdd301a3ffacc14093fa6fc472952
