### ISSUE TITLE
Compilation fails on Debian 10

### ISSUE THREAD

**Issue by siyia2** [google/shaderc#567]
cmake -GNinja -DCMAKE_BUILD_TYPE=Release
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Shaderc: build type is "Release".
-- Configuring Shaderc to build tests.
CMake Error at third_party/CMakeLists.txt:31 (message):
  gmock was not found - required for tests

-- Configuring incomplete, errors occurred!
 
and yes i have installed google-mock

**Comment by fjhenigman** [comment]
Did you run utils/git-sync-deps in your source directory?

**Comment by siyia2** [comment]
yea that's it i forgot to run utils/git-sync-deps, closing....
