### ISSUE TITLE
Cannot build on Ubuntu, GCC, Unix Makefiles

### ISSUE THREAD

**Issue by Crisspl** [google/shaderc#568]
We're trying to integrate shaderc into our project using CMake, as suggested here https://github.com/google/shaderc/tree/master/libshaderc. However regardless if I `target_link_libraries(ourtarget shaderc)` or `target_link_libraries(ourtarget shaderc_combined)`, I get
```
No rule to make target '3rdparty/shaderc/libshaderc/libshaderc_combined.a', needed by '3rdparty/shaderc/libshaderc/CMakeFiles/shaderc_combined_genfile'`.
```
The error concerns those lines (actually the second one) in Makefile2 file:
```
3rdparty/shaderc/libshaderc/CMakeFiles/shaderc_combined_genfile.dir/all:
    $(MAKE) -f 3rdparty/shaderc/libshaderc/CMakeFiles/shaderc_combined_genfile.dir/build.make 3rdparty/shaderc/libshaderc/CMakeFiles/shaderc_combined_genfile.dir/depend
    $(MAKE) -f 3rdparty/shaderc/libshaderc/CMakeFiles/shaderc_combined_genfile.dir/build.make 3rdparty/shaderc/libshaderc/CMakeFiles/shaderc_combined_genfile.dir/build
    @$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --progress-dir=/home/criss/IrrlichtBAW/build/CMakeFiles --progress-num= "Built target shaderc_combined_genfile"
.PHONY : 3rdparty/shaderc/libshaderc/CMakeFiles/shaderc_combined_genfile.dir/all
```

It builds fine on Windows (MSVC, Visual Styudio 2017) with `target_link_libraries(ourtarget shaderc)` (plus actually `add_dependency(ourtarget shaderc)` is needed to get correct build order)

**Comment by fjhenigman** [comment]
The following simple CMakeLists.txt worked for me
```
add_subdirectory(shaderc)
add_executable(blah main.cc)
target_link_libraries(blah shaderc)
```

Can you show your cmake code, ideally trimmed down to a minimal example?

**Comment by Crisspl** [comment]
As for now I'll just show full version of cmake:
This is where is `target_link_libraries`: https://github.com/Crisspl/IrrlichtBAW/blob/master/source/Irrlicht/CMakeLists.txt#L325
This is root CMakeLists: https://github.com/Crisspl/IrrlichtBAW/blob/master/source/Irrlicht/CMakeLists.txt#L325
And here, in `3rdparty/CMakeLists.txt`, is actual `add_subdirectory(shaderc)`: https://github.com/Crisspl/IrrlichtBAW/blob/master/3rdparty/CMakeLists.txt
The approach is taken from [shaderc-rs](https://github.com/google/shaderc-rs/blob/master/build/CMakeLists.txt).

The only other dependency of IrrlichtBAW is openssl, so may be you can even run it yourself if you've got some more time. It's hard to make it as minimal example, because I have no idea how I could limit the script to things that could be the origin of troubles. However I'll try to reproduce this in error in simpler form tomorrow, if you won't be able to find a possible cause just in a moment. However I can be sure that I can limit the area where could be the problem to those three CMakeLists files I linked above.

**Comment by fjhenigman** [comment]
I cloned your github project and tried to build and I saw the problem.
Ninja had the same problem as make so I guess it is a problem with the cmake stuff but I'm still trying to figure it out.
I was able to proceed with the build after doing "touch 3rdparty/shaderc/libshaderc/libshaderc_combined.a"

**Comment by Crisspl** [comment]
Seems like a working workaround. Thank you for your help! I'm closing then and I'll reopen if I come across related problems. Thanks!

**Comment by fjhenigman** [comment]
I tracked it down to this bit of code:
https://github.com/google/shaderc/blob/94f21e8f3c1172095dacefb5b494f9bb18cbba13/cmake/utils.cmake#L166

The problem occurs when there are multiple configurations, as in the reporter's case.
We might be using CMAKE_CFG_INTDIR wrong.  The manual says "this variable is suitable only for use in command lines that will be evaluated at build time."
When the problem occurs this variable contains "." and $libname gets "./libshaderc_combined.a"
When we avoid that section $libname contains an absolute path and everything works.
Not really sure how this should work, but I'll take a stab at fixing anyway.

**Comment by AWoloszyn** [comment]
I think this is a problem with the downstream CMake file.

https://cmake.org/cmake/help/v3.0/variable/CMAKE_CONFIGURATION_TYPES.html
```
Specifies the available build types on multi-config generators.
```

The downstream project is setting this for single config generator. (Make/Ninja are not multi-config generators. They can only configure for a single platform at a time).

This CMake variable should not be set in these cases.

**Comment by AWoloszyn** [comment]
If we can figure out a different/better way to determine if the generator requires INT_DIR, then that should work, but at the time, this was the most straight-forward way to figure this out.
