### ISSUE TITLE
Fix appveyor to build x64 build targets on Windows

### ISSUE THREAD

**Issue by nvining-work** [google/shaderc#580]
In order for shaderc's precompiled DLL to be used on Windows in a 64-bit environment, we need a 64-bit DLL. It would be convenient (and probably also a good idea for testing purposes!) to have this built by Appveyor as part of the build process. Thanks!

**Comment by fjhenigman** [comment]
We don't use appveyor anymore, we use kokoro, which at present does not save build products.
I'll work on that.

**Comment by fjhenigman** [comment]
How do we want to package the build?  We can zip the install dir and/or something fancier?
@dneto0

**Comment by fjhenigman** [comment]
I think I figured out how to make the download buttons on the README page work.
There are currently three non-functioning buttons: Linux, MacOS, Windows.
Do we want more?  If not which builds do they point at?  We have release/debug, gcc/clang, MSVS 2013/15/17.
@dneto0

**Comment by nvining-work** [comment]
My suggestion would be that Windows should be packaged as a ZIP and Linux/OSX should be packaged as .tar.gz. I'm not sure what goes into it otherwise, though. I think you need release/debug, gcc/clang/MSVC 2013/15/17; however, the MSVC 2013/2015/2017 builds ought to have both 32-bit and 64-bit release/debug builds.

I have no idea what the right thing is for the MSVC builds to link against in terms of runtimes. I think /MT and /MDd for Release and Debug respectively. YMMV.

**Comment by fjhenigman** [comment]
We only have 64-bit Windows builds at present.  @dneto0 shall I try to add 32-bit?

**Comment by nvining-work** [comment]
Ah - the original appveyor build is 32-bit. I think the 64-bit build is *probably* good enough, but I don't know how much dneto cares about completeness :)

**Comment by nvining-work** [comment]
FYI somebody who has the ability to do so should mark https://github.com/google/shaderc/issues/414 as a dupe of this

**Comment by dneto0** [comment]
I'd only do the 64bit windows for now.  If someone wants 32-bit then they can ask for it.

**Comment by fjhenigman** [comment]
All the download buttons on the [home page](https://github.com/google/shaderc) should work now.
I added a [secondary download page](https://github.com/google/shaderc/blob/master/downloads.md) with the full menu, so as not to clutter the home page too much.  Link is right below the home page buttons.

That give access to the latest builds.  To see older builds you can browse the [cloud storage](https://console.cloud.google.com/storage/browser/shaderc/artifacts/prod/graphics_shader_compiler/shaderc/).  You will have to sign in to a google account to do that, but anyone can do it.  We can provide a friendlier interface to old builds in the future, if necessary.
