### ISSUE TITLE
Parallelize tests being run by run_spirv_cross_tests.py

### ISSUE THREAD

**Issue by zoddicus** [google/shaderc#611]
Currently the long pole for running ctest is spvc_spirv_cross_tests, which takes up 189 of 309 secs to run. This is because it is running all of the test inputs in spriv-cross, twice I believe, once for a baseline and one for testing. This is thousands of runs.

The baseline results could be cached, which significantly lower the computation requirements, but that requires implementing a caching and refreshing mechanism. This should be done at some point, but for an initial low hanging fruit, just make the tests complete sooner option I am looking at parallalizing these operations, since they already run in separate processes. I will either break up the test set into multiple blocks at the cmake level, so that -j can be passed to ctest, or I will use concurrency in the test runner itself.

**Comment by zoddicus** [comment]
Talked with dneto about this, going to focus on parallel processing within the Python script.

**Comment by fjhenigman** [comment]
Some of the test shaders are run more than once, but with different options.  I wouldn't bet my life but I don't think there's any needless duplicated work.

Another option for speed-up is to avoid starting so many processes.  If everything happened in one process I bet it wouldn't take long to run.  Admittedly you'd have to write a bunch of C++ code and lose the convenience of having the test script in python.  On the other hand, there might be something in ctest and/or googletest which would then give you parallelism for free?
