### ISSUE TITLE
Migrate DEPS to same format as chromium

### ISSUE THREAD

**Issue by zoddicus** [google/shaderc#662]
This is needed for getting an auto-roller running.

The change that is needed is specifically 'vars['xyz''] to Var('xyz')', but this will require change git-sync-deps also

**Comment by dj2** [comment]
Why is this necessary? The skia auto-roller doesn't work with the skia git-sync-deps script? Isn't it just python being read in both cases?

**Comment by zoddicus** [comment]
Apparently not. Autoroller depends on gclient from depot_tools, which in spite of it document saying that the DEPS is a python script, does not actually tree it as such, since there are things like Var() instead of vars[] going on.
