### ISSUE TITLE
Problem building dockerfile

### ISSUE THREAD

**Issue by olofwalker** [google/shaderc#666]
Hi,

When I try to build the dockerfile included in this project (from master) I get the following error message:

```
Step 7/16 : RUN ./utils/git-sync-deps
 ---> Running in 6feef758c7f1
Traceback (most recent call last):
  File "./utils/git-sync-deps", line 60, in <module>
    from builtins import bytes
ImportError: No module named builtins
```

The only way I can get the docker file to successfully build is to change `python` to `python3` and install the pip module `future`, then it works, below follows my version of the dockerfile.

```
FROM alpine

MAINTAINER Google Shaderc Team

RUN apk add --update \
    build-base \
    cmake \
    git \
    ninja \
    python3 \
    py-pip \
    && rm -rf /var/cache/apk/*

RUN pip install future

WORKDIR /root
RUN git clone https://github.com/google/shaderc

WORKDIR shaderc
RUN ./utils/git-sync-deps

WORKDIR build
RUN cmake -GNinja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr/local \
    .. \
    && ninja install

WORKDIR /root
RUN rm -rf shaderc

RUN adduser -s /bin/sh -D shaderc
USER shaderc

VOLUME /code
WORKDIR /code

CMD ["/bin/sh"]
```

I'm using Ubuntu 18.04.

**Comment by zoddicus** [comment]
I am not surprised that you need Python3, since we did update everything to Python 3 recently and apparently the Dockerfile got missed. I am mildly surprised that you need to add future package since that is a Python2-ism. It looks like there is a test script that was missed. I will take a look at updating this.
