### ISSUE TITLE
Need some sort of smoketest for downstream dependencies like chromium and dawn

### ISSUE THREAD

**Issue by zoddicus** [google/shaderc#674]
Once we have autorollers setup for shaderc and Dawn I think it might be worthwhile to have some sort of smoketest as part of the bots in shaderc that would give you warning if you were introducing a breaking change. I am thinking maybe something just tries to build the targets that depend on shaderc. I will have to think about this more in the future.

**Comment by dneto0** [comment]
Shaderc is relatively inactive.  So our team went with a smoketest in SPIRV-Tools instead. 

https://github.com/KhronosGroup/SPIRV-Tools/tree/master/kokoro/shaderc-smoketest
