### ISSUE TITLE
Add shaderc_compile_options_set_target_spirv API

### ISSUE THREAD

**Issue by dneto0** [google/shaderc#742]
This requirement comes from https://github.com/google/amber/issues/549

The idea is to be able to refine the target environment with a specific version of SPIR-V to be generated by the underlying compiler.  Glslang already has this API, but it has not yet been exposed at the Shaderc level.

-----------

Shaderc changes:
Summary: add ability to override SPIR-V version generated by the compiler.
Avoid mixing enums for client API with SPIR-V version override. (Match Glslang)

add enum shaderc_spirv_version {
shaderc_spirv_version_1_0
shaderc_spirv_version_1_1
shaderc_spirv_version_1_2
shaderc_spirv_version_1_3
shaderc_spirv_version_1_4

add shaderc_compile_options_set_target_spirv
sets the SPIR-V version of the generated module.
overrides default compilation, which is highest spir-v version in core of target env:
vulkan1.0 -> spir-v 1.0
vulkan1.1 -> spir-v 1.3
OpenGL* -> spir-v 1.0

document interaction with shaderc_get_spv_version
That doesn't know the shaderc_compile_options object, so it can't answer
correctly. So update the description to say it's the max version known
by Shaderc. It's the spv::Version and spv::Revision reported by the
SPIRV-Headers we compiled with.
libshaderc_util::Compiler

add enum SpirvVersion {
// corresponding to shaderc_spirv_version
SPIRV_1_0, SPIRV_1_1, .... }

add method SetTargetSpirv
// Sets the forced version of SPIR-V on the generated module.
// Default is the highest version of SPIR-V required
// to be supported by the target environment.
// e.g. Vulkan 1.0 -> SPIR-V 1.0
// e.g. Vulkan 1.1 -> SPIR-V 1.3
// (Recall target environment defaults to Vulkan 1.0)

Compiler methods:

already call Glslang's setEnvClient to set client API version
if SetSpirvVersion has been called, then use those values in the
Glslang setEnvTarget.

**Comment by maeln** [comment]
Hi! 

My own project is limited by libshaderc not able to choose the generated SPIR-V version.
This feature would be very very much appreciated <3 !

Faithfully yours,

**Comment by dneto0** [comment]
Fixed with https://github.com/google/shaderc/pull/750
