### ISSUE TITLE
spvc: Add option to inject code to enforce robust-buffer-access 

### ISSUE THREAD

**Issue by dneto0** [google/shaderc#767]
See the spirv-opt transform being added via https://github.com/KhronosGroup/SPIRV-Tools/pull/2771 
This is useful when an implementation does not support robust-buffer access as a driver option.  This pass modifies the SPIR-V code to do its own index and coordinate clamping.

**Comment by zoddicus** [comment]
@sarahM0 if you are wanting a starter bug that deals more with the API of spvc vs the integration with spirv-cross, this would probably be a good one to look at.
