### ISSUE TITLE
Archive architecture linking problem

### ISSUE THREAD

**Issue by jenvannier** [google/shaderc#77]
So I build according to the README (cmake -GNinja -DCMAKE_BUILD_TYPE=Release ../)

and then as I need to use option 3 in shaderc/libshaderc's README I link in libshaderc_combined.a and include libshaderc/include, all on the same computer (and ergo same architecture)

But when I try to compile my code I get this warning:
> ld: warning: ignoring file libshaderc/libshaderc_combined.a, file was built for archive which is not the architecture being linked (x86_64): libshaderc/libshaderc_combined.a

and when I run lipo -info on libshaderc_combined.a I get:
>fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: archive with no architecture specification: libshaderc/libshaderc_combined.a (can't determine architecture for it)

But even when I had converted the libshaderc_combined so lipo recognized it as x86_64 I was getting the same warning.

And because of the warning when I run my code I get:
> dyld: lazy symbol binding failed: Symbol not found: _shaderc_compiler_initialize
  Referenced from: shader
  Expected in: flat namespace

Any ideas?

**Comment by dekimir** [comment]
Sorry to hear you're having trouble, @jenvannier .  I see you're building on MacOS, right?  I recall a recent change (#51) that specifically impacted how `.a` files are created on MacOS.  You may need to use `libtool` to link your code against `libshaderc_combined.a`.

**Comment by antiagainst** [comment]
Hi @jenvannier, I suspect the issue is `libstdc++` vs `libc++` on Mac. Could you try whether adding `-stdlib=libc++` in [`default_compile_options()`](https://github.com/google/shaderc/blob/master/cmake/utils.cmake#L12) works for you? (And maybe also  add `-stdlib=libc++` to your code's build configuration.)

**Comment by jenvannier** [comment]
Adding -stdlib=libc++ in default_compile_options() fixed it! Now it's all working perfectly. Thank you!
