### ISSUE TITLE
UnicodeDecodeError with Python3

### ISSUE THREAD

**Issue by MulattoKid** [google/shaderc#778]
When following the build instructions, I got an error when issuing the 'ninja' build command. This happend on a fresh clone of the repo:
```
git clone https://github.com/google/shaderc.git
cd shaderc
./utils/git-sync-deps
git checkout known-good
./update_shaderc_sources.py
git checkout master
mkdir build && cd build
cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
ninja

[6/756] Update build-version.inc in the Shaderc build directory (if necessary).
FAILED: CMakeFiles/build-version 
cd /home/danlar02/WorkDir/shaderc/build && /usr/bin/python3 /home/danlar02/WorkDir/shaderc/utils/update_build_version.py /home/danlar02/WorkDir/shaderc /home/danlar02/WorkDir/shaderc/third_party/spirv-tools /home/danlar02/WorkDir/shaderc/third_party/glslang
Traceback (most recent call last):
  File "/home/danlar02/WorkDir/shaderc/utils/update_build_version.py", line 137, in <module>
    main()
  File "/home/danlar02/WorkDir/shaderc/utils/update_build_version.py", line 125, in main
    for (p, d) in zip(projects, sys.argv[1:])
  File "/home/danlar02/WorkDir/shaderc/utils/update_build_version.py", line 125, in <listcomp>
    for (p, d) in zip(projects, sys.argv[1:])
  File "/home/danlar02/WorkDir/shaderc/utils/update_build_version.py", line 111, in get_version_string
    detailed_version_string_lst.append(deduce_software_version(directory))
  File "/home/danlar02/WorkDir/shaderc/utils/update_build_version.py", line 67, in deduce_software_version
    for line in f.readlines():
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 826: ordinal not in range(128)
[23/756] Building CXX object third_party/googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
ninja: build stopped: subcommand failed.
```

Changing all 'python3' commands to use 'python2' in build/build.ninja fixed the issue, but seems there's something wrong?

I'm running Python 3.6.8 on Ubuntu 18.04.2

**Comment by zoddicus** [comment]
Sound like we have a missed python2-ism somewhere. We are supposed to be using Python3 everywhere now. I will have to take a look at update_build_version.py and see what is up.

**Comment by zoddicus** [comment]
So I haven't been able to reproduce this issue locally, but have a provisional fix. I think the root cause is that Python2 and Python3 have slightly different behaviour when encountering Unicode in an ASCII file. I was not able to determine where the unicode character was being read from, but I have changed the behaviour in Python3 to be more robust and not error out.

I have created a PR with my fix in it, #783. Could you try patching this into your checkout and see if it resolves your problem?

**Comment by MulattoKid** [comment]
Yup, the patch fixes the issue :)

**Comment by zoddicus** [comment]
Just re-opening since the patch is still pending, once it lands, this should re-close.
