### ISSUE TITLE
Investigate refactoring spvc code to use wrappers for spirv-tools from libshaderc_utils

### ISSUE THREAD

**Issue by zoddicus** [google/shaderc#800]
Currently this code directly calls into the spirv-tools API. libshader_utils has some utility/wrappers for these APIs that might be useful. This needs to be investigated. There may need to be additional wrappers added if some of the tools that spvc uses are not already covered.

**Comment by sarahM0** [comment]
libshadrc_util is dependent on glslang library. Which means for using spvtools wappers we need to include glslang in spv and that is not ideal.

A long term solution would be rewriting shaderc_util to have three different targets:
1- generic or no dependency
2- depending on spirv tools
3- depending on spirv tools and glslang
