### ISSUE TITLE
HLSL Bindings issue

### ISSUE THREAD

**Issue by QuantumDeveloper** [google/shaderc#858]
In HLSL we could register different resources with the same ids. For example,
```
sampler sampleType : register(s0);
cbuffer Matrices : register(b0)
{
	matrix wvp;
	float4 fillColor;
};
```
And in SPIR-V output we will have same ids for different resources (in this case we will have both 0) which is unacceptable for Vulkan. I know we could define binding shift for each resource, but this seems to me also not so convenient especially in case of automatically processing of shaders. In this case you cannot be sure on what value it will be safe to shift  binding.

So, my question is: Is this a bug or a feature?

**Comment by dneto0** [comment]
Shader binding strategies is very much tied with how your engine is set up.
You need an allocation strategy that works with the rest of your allocation.

Shaderc wraps around Glslang, and exposes most of the binding-shifting options from Glslang.
Also, Glslang's HLSL support allows [[vk::binding(...)]] attributes. See examples at https://github.com/KhronosGroup/glslang/blob/master/Test/hlsl.attributeC11.frag 

Both Glslang and DXC's Vulkan backend support the same in-shader binding rules.  (The engineers collaborated.)
So I recommend you consult the DXC SPIR-V documentation at:
https://github.com/microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#hlsl-register-and-vulkan-binding

**Comment by QuantumDeveloper** [comment]
@dneto0 Thanks for your answer, but can you clarify one more point?
How to use binding shifting in shaderc?
I think the closest way is to use `SetHlslRegisterSetAndBinding` and `SetHlslRegisterSetAndBindingForStage`, but what will be the exact equivalent for `-fvk-t-shift 10 0` for example?
Like `SetHlslRegisterSetAndBinding(opts, ???, "0", "10")`
