### ISSUE TITLE
Includer callback does not work correctly?

### ISSUE THREAD

**Issue by QuantumDeveloper** [google/shaderc#859]
I am trying to compile shader with includes and I am using `shaderc_compile_options_set_include_callbacks`. 
In the includer callback I have almost completely invalid data. All input parameters are come to me invalid except user_data parameter. It contains parsed raw string to the include file. Two other string parameters are always null and `type` parameter with `include_depth` contains some inconsistent values which has no sense. For example, `type` comes to me with value `1682405456` and `include_depth` contains `140715242437289`, which is as for me completely incorrect data.

Then I tried to change char* parameters in callback with int and size_t parameters correspondingly and it partially worked. At least, value for `requested_source` became correct, but `requesting_source` still has no sense.

P.S. I am using C# bindings to the C part of shaderc and define my delegate like this:
`[UnmanagedFunctionPointer(CallingConvention.Winapi)]
public delegate ShadercIncludeResult ShadercIncludeResolveFn([In] System.IntPtr user_data, [In] int type, IntPtr requested_source, [In] ulong include_depth, IntPtr requesting_source);`
So, seems there is no issues with marshaling intself.

Could you please confirm that issue with includes really exists?

**Comment by QuantumDeveloper** [comment]
Any comments on this issue from anyone?

**Comment by dneto0** [comment]
This API is used in the C++ interface to Shaderc:   https://github.com/google/shaderc/blob/master/libshaderc/include/shaderc/shaderc.hpp#L201

And that in turn is used by glslc to do filesystem-based inclusion:  https://github.com/google/shaderc/blob/master/glslc/src/file_compiler.cc#L91

We have tests showing that glslc inclusion feature works: https://github.com/google/shaderc/blob/master/glslc/test/include.py

So my guess is that your bindings are not as you expect.

**Comment by QuantumDeveloper** [comment]
@dneto0 
Given the behavior is more likely memory corruption6 because when I go outside callback, I am receiving NullReferenceException (which is completely C# exception type of course)

The funny thing here is that in Vulkan I am using the same way of interaction using delegates and it works without errors...

I will look into this issue more carefully and try to find out what is wrong here. Will write a feedback soon

**Comment by QuantumDeveloper** [comment]
@dneto0 
I double checked my bindings and seems you were right. I found some errors in my delegates marshaling (hello to pointers). After I fixed it, everything seems working fine.

Thanks for pointing in the right direction.
