### ISSUE TITLE
Need NDK build instructions and android binaries

### ISSUE THREAD

**Issue by ggfan** [google/shaderc#875]
The download page does not have libshaderc.a for Android Target,I tried to download the windows(host) version, could not find inside "lib" directory: libshaderc.a . ( the combined one )

Could not find instruction on how to build for Android

Shaderc code inside NDK throws errors when build under windows ( Linux builds fine )

May you kindly help to get the Android Target + Windows Host?  thank you so much!

**Comment by sfricke-samsung** [comment]
I was able to build for Android via CMake from ToT

`cmake -DANDROID_ABI=arm64-v8a -DCMAKE_BUILD_TYPE=Release -DANDROID_STL=c++_static -DANDROID_PLATFORM=android-24 -DCMAKE_SYSTEM_NAME=Android -DANDROID_TOOLCHAIN=clang -DANDROID_ARM_MODE=arm C:\ndk\build\cmake\android.toolchain.cmake`

**Comment by ggfan** [comment]
thanks!
