### ISSUE TITLE
Add a Kokoro build, running spvc parser and tests

### ISSUE THREAD

**Issue by sarahM0** [google/shaderc#877]

**Comment by zoddicus** [comment]
I am likely going to need to change the current spvc parser build flag over to being a runtime toggle, to support Dawn integration. If I do that, we will not have to create a separate Kokoro build, but instead will have to modify the existing builds to run with that toggle flipped on and off.

**Comment by zoddicus** [comment]
I added a comment in https://github.com/google/shaderc/pull/901 for the tests that need to be re-enabled. I tried to turn them on, but it was generating a large number of failures. All of the plumbing should be done for enabling/disabling the IR parser, it is just the test expectations that need to be updated.

**Comment by zoddicus** [comment]
spvc has been deprecated and removed.
