### ISSUE TITLE
Add 'negative' unit tests to IR generation code

### ISSUE THREAD

**Issue by zoddicus** [google/shaderc#889]
The tests that are being added currently are overwhelmingly 'positive' tests, i.e. ones that confirm correct behaviour under valid inputs. This is sufficient for implementing the parser, but for robustness 'negative' tests, i.e ones that test correct behaviour under invalid inputs, should be added.

In theory the use of spirv-val and spirv-opt ahead of the IR generation should prevent any invalid inputs from reaching this layer, but there could always be bugs.

**Comment by sarahM0** [comment]
Examples:
Bounds check, do one high and one low see if they work.
OpExtension, pass in garbage strings as extension.

**Comment by zoddicus** [comment]
spvc has been deprecated and removed.
