### ISSUE TITLE
DEPS failing due to failing glslc tests 

### ISSUE THREAD

**Issue by zoddicus** [google/shaderc#996]
PR that is failing:
https://github.com/google/shaderc/pull/995
Win 2015 & 2017 bots are failing specifically,
https://source.cloud.google.com/results/invocations/95269cd3-f3d9-4d0c-8187-f18d4e3ac982/targets/graphics_shader_compiler%2Fshaderc%2Fwindows%2Fpresubmit_release_2017/log

I suspect that is something from the glslang part of the roll.

**Comment by dj2** [comment]
VKB roll: https://github.com/google/vkb/pull/82

**Comment by dneto0** [comment]
I'm testing locally on windows
  - current shaderc with its current DEPS passes
  - above, and with top-of-tree SPIRV-Headers and SPIRV-Tools passes
  - above, with Glslang at c6a4c6d3 passes
  - above, with Glslang 6f230b9e0b fails. That's the GL_EXT_debug_printf implementation https://github.com/KhronosGroup/glslang/pull/2098

**Comment by dneto0** [comment]
Capturing for ease of examination:  The failures are from this include test:  
https://github.com/google/shaderc/blob/master/glslc/test/include.py#L508


```
29/399     VerifyDashIAbsolutePath                  -Failed-
T:/src/github/shaderc/build/glslc/glslc.exe -E a.vert -I T:\src\github\shaderc\build\glslc\test\tmpavggnnem/foo
Incorrect stdout output:
b''
Expected:
#version 140
#extension GL_GOOGLE_include_directive : enable
#line 0 "a.vert"

content a
#line 0 "T:\src\github\shaderc\build\glslc\test\tmpavggnnem/foo/b.glsl"
 content b
#line 3 "a.vert"

```
And 
```
38/399     VerifyRelativeFromAbsolutePath           -Failed-
T:/src/github/shaderc/build/glslc/glslc.exe -E T:\src\github\shaderc\build\glslc\test\tmpotme9zeg/a.vert
Incorrect stdout output:
b''
Expected:
#version 140
#extension GL_GOOGLE_include_directive : enable
#line 0 "T:\src\github\shaderc\build\glslc\test\tmpotme9zeg/a.vert"

content a
#line 0 "T:\src\github\shaderc\build\glslc\test\tmpotme9zeg/b.glsl"
 content b
#line 3 "T:\src\github\shaderc\build\glslc\test\tmpotme9zeg/a.vert"

```
