### ISSUE TITLE
Enum size for wrappers

### ISSUE THREAD

**Issue by jpbruyere** [google/shaderc#998]
Is it possible to populate all enums with a MAX value (fixed size for all, 16 or 32 bit filled with 1) to help wrappers with a fixed enum size? This is already the case in the vulkan library. Thank you in advance.

**Comment by zoddicus** [comment]
@dneto0 thoughts?

**Comment by dj2** [comment]
A similar change in GLSLang cause a lot of issues downstream as warnings about non-covering switches started firing and having to be fixed.

Is the benefit just to make it easier to write the wrapper automatically? Otherwise, what's the benefit?

**Comment by jpbruyere** [comment]
That's it, I try to make a wrapper generator. But ok, I think I can go with dynamic sizing of enums, I'll try without it, thanks for your replies.
